### ISSUE TITLE
RoslynTester NuGet package pulls in NUnit, why?

### ISSUE THREAD

**Issue by tiesmaster** [Vannevelj/RoslynTester#10]
I've replaced the default unit test code of my analyzers, with that of RoslynTester (thanks btw, for putting that in a nuget package ;). However, I noticed that it also pulled in NUnit. Is that really necessary?

I'm using Xunit, instead of NUnit, so I don't need it. Should RoslynTester really depend on NUnit?

**Comment by Vannevelj** [comment]
I don't think it's necessary to have either package as a dependency. In the end, all that we really do with it are comparing and numbers. I'll take a look and see if that is an option to get rid of the dependencies altogether.

**Comment by tiesmaster** [comment]
Ok, cool. I know that FluentAssertions doesn't pull in every possible TDD framework, and are still able to fail unit tests for them. I don't know how they do it, but maybe we could use that approach?

**Comment by Vannevelj** [comment]
I released a new version of RoslynTester on NuGet, that should take care of this. Let me know if you encounter a problem with it!

https://github.com/Vannevelj/RoslynTester/releases/tag/v1.5.0
https://www.nuget.org/packages/RoslynTester/1.5.0

**Comment by tiesmaster** [comment]
Nice, thanks!

I just upgraded, and tried it out, and the verification of the fix gives a false positive. Breaking the analyzer test works perfectly, but the verification of the fix doesn't. I also tried it with the previous version of RoslynTester, and the fix did fail there. I'm guessing it's a combination of the custom assertions, and perhaps Xunit.

I'll dig a little deeper tonight.

**Comment by Vannevelj** [comment]
hmm.. I've tested it with the 600 tests we have in VSDiagnostics and they all worked as they should. I've found a piece of code that I think might cause an issue although it surprises me that it didn't for any of our tests. Would you mind trying out this dll and see if it fixes your issue?

https://mega.nz/#!RUdw3L6J!FSeTG8nsresp1Y3biQxRYAAAWifWhB9RMd8bUHGl_4E

**Comment by tiesmaster** [comment]
Just a heads up, I wasn't able to test this yesterday evening, and I'm swamped the rest of the week, so it may take some time before I can give you feedback about this. Sorry for that.

**Comment by Vannevelj** [comment]
No problem, feel free to do it when you have the time for it.

**Comment by tiesmaster** [comment]
I was finally able to work on this again ;) Luckily, I wasn't able to reproduce the problem, so it's working as expected :+1:

**Comment by Vannevelj** [comment]
Perfect! You'll notice that the v1.5.0 release is hidden from NuGet because we had concerns about this issue and another one that caused VB.NET stuff to be handled incorrectly. Since these two issues are now resolved, we'll release v1.6.0 with some added new functionality as soon as I'm home -- which is in a week.

I'm not sure if you can still use the NuGet v1.5.0 release so you might want to hold on to that dll for the time being otherwise.

**Comment by tiesmaster** [comment]
Cool. I'll wait, that's no problem ;)
